### ISSUE TITLE
Zoom Limitations and Performance Issues

### ISSUE THREAD

**Issue by odest** [odest/DonkeyDoc#1]
Application currently lacks any zoom limits, which results in performance degradation and errors under extreme zoom levels. Specifically:

1. **Zoom In**: When zooming in beyond a certain point, the application starts to lag significantly.

2. **Zoom Out**: When zooming out excessively, there comes a point where the document disappears or becomes invisible, causing the application to throw an error.

**Expected Behavior:**
- Implement zoom limits to prevent excessive zooming in or out.
- Ensure that the application maintains performance and stability within reasonable zoom ranges.

**Comment by LyubomirT** [comment]
Really excited to contribute to this project. :)

Can I try to add zoom limits?

**Comment by odest** [comment]
Of course you can add it, I would be very pleased

**Comment by prangowda** [comment]
To fix the zoom problem, set limits so users can't zoom in too much or zoom out so far that things disappear. This will keep the app running smoothly and prevent errors.
